// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenMedSphere.Domain.ValueObjects;
using OpenMedSphere.Infrastructure.Persistence;

#nullable disable

namespace OpenMedSphere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209084435_SeedAnonymizationPolicies")]
    partial class SeedAnonymizationPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.AnonymizationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("GeneralizeDateOfBirth")
                        .HasColumnType("boolean");

                    b.Property<bool>("GeneralizeLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("KAnonymityThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SuppressRareDiagnoses")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("AnonymizationPolicies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "No anonymization applied. Data remains in its original form.",
                            GeneralizeDateOfBirth = false,
                            GeneralizeLocation = false,
                            IsActive = true,
                            Level = "None",
                            Name = "No Anonymization",
                            SuppressRareDiagnoses = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Removes direct identifiers such as name, address, and SSN.",
                            GeneralizeDateOfBirth = false,
                            GeneralizeLocation = false,
                            IsActive = true,
                            Level = "Basic",
                            Name = "Basic Anonymization",
                            SuppressRareDiagnoses = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Removes direct identifiers and generalizes quasi-identifiers such as date of birth and location.",
                            GeneralizeDateOfBirth = true,
                            GeneralizeLocation = true,
                            IsActive = true,
                            Level = "Standard",
                            Name = "Standard Anonymization",
                            SuppressRareDiagnoses = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Applies k-anonymity, generalization, and suppression techniques to prevent re-identification.",
                            GeneralizeDateOfBirth = true,
                            GeneralizeLocation = true,
                            IsActive = true,
                            KAnonymityThreshold = 5,
                            Level = "Advanced",
                            Name = "Advanced Anonymization",
                            SuppressRareDiagnoses = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Applies differential privacy techniques and maximum generalization for the highest level of privacy protection.",
                            GeneralizeDateOfBirth = true,
                            GeneralizeLocation = true,
                            IsActive = true,
                            KAnonymityThreshold = 5,
                            Level = "Full",
                            Name = "Full Anonymization",
                            SuppressRareDiagnoses = true
                        });
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.PatientData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonymizationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnonymizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryDiagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("_medications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Medications");

                    b.PrimitiveCollection<string>("_secondaryDiagnoses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("SecondaryDiagnoses");

                    b.Property<List<MedicalCode>>("_secondaryDiagnosisCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("SecondaryDiagnosisCodes");

                    b.HasKey("Id");

                    b.HasIndex("AnonymizationPolicyId");

                    b.HasIndex("CollectedAtUtc");

                    b.HasIndex("IsAnonymized");

                    b.HasIndex("PrimaryDiagnosis");

                    b.HasIndex("Region");

                    b.ToTable("PatientData", (string)null);
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.ResearchStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnonymizationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<string>("PrincipalInvestigator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResearchArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("_patientDataIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("PatientDataIds");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StudyPeriod", "OpenMedSphere.Domain.Entities.ResearchStudy.StudyPeriod#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StudyPeriodEnd");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StudyPeriodStart");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AnonymizationPolicyId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ResearchArea");

                    b.ToTable("ResearchStudies", (string)null);
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.PatientData", b =>
                {
                    b.OwnsOne("OpenMedSphere.Domain.ValueObjects.MedicalCode", "PrimaryDiagnosisCode", b1 =>
                        {
                            b1.Property<Guid>("PatientDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PrimaryDiagnosisCode_Code");

                            b1.Property<string>("CodingSystem")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PrimaryDiagnosisCode_CodingSystem");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PrimaryDiagnosisCode_DisplayName");

                            b1.Property<string>("EntityUri")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PrimaryDiagnosisCode_EntityUri");

                            b1.HasKey("PatientDataId");

                            b1.ToTable("PatientData");

                            b1.WithOwner()
                                .HasForeignKey("PatientDataId");
                        });

                    b.OwnsOne("OpenMedSphere.Domain.ValueObjects.PatientIdentifier", "PatientId", b1 =>
                        {
                            b1.Property<Guid>("PatientDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PatientIdentifier");

                            b1.HasKey("PatientDataId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_PatientData_PatientIdentifier");

                            b1.ToTable("PatientData");

                            b1.WithOwner()
                                .HasForeignKey("PatientDataId");
                        });

                    b.Navigation("PatientId")
                        .IsRequired();

                    b.Navigation("PrimaryDiagnosisCode");
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.ResearchStudy", b =>
                {
                    b.OwnsOne("OpenMedSphere.Domain.ValueObjects.StudyCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("ResearchStudyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("StudyCode");

                            b1.HasKey("ResearchStudyId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_ResearchStudies_StudyCode");

                            b1.ToTable("ResearchStudies");

                            b1.WithOwner()
                                .HasForeignKey("ResearchStudyId");
                        });

                    b.Navigation("Code")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
