// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenMedSphere.Domain.ValueObjects;
using OpenMedSphere.Infrastructure.Persistence;

#nullable disable

namespace OpenMedSphere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.AnonymizationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("GeneralizeDateOfBirth")
                        .HasColumnType("boolean");

                    b.Property<bool>("GeneralizeLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("KAnonymityThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SuppressRareDiagnoses")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("AnonymizationPolicies", (string)null);
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.PatientData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonymizationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnonymizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAnonymized")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("Medications")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryDiagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string>("SecondaryDiagnoses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<MedicalCode>>("SecondaryDiagnosisCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PatientId", "OpenMedSphere.Domain.Entities.PatientData.PatientId#PatientIdentifier", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PatientIdentifier");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IsAnonymized");

                    b.HasIndex("PrimaryDiagnosis");

                    b.ToTable("PatientData", (string)null);
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.ResearchStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnonymizationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("PatientDataIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrincipalInvestigator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResearchArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Code", "OpenMedSphere.Domain.Entities.ResearchStudy.Code#StudyCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("StudyCode");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StudyPeriod", "OpenMedSphere.Domain.Entities.ResearchStudy.StudyPeriod#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StudyPeriodEnd");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StudyPeriodStart");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ResearchArea");

                    b.ToTable("ResearchStudies", (string)null);
                });

            modelBuilder.Entity("OpenMedSphere.Domain.Entities.PatientData", b =>
                {
                    b.OwnsOne("OpenMedSphere.Domain.ValueObjects.MedicalCode", "PrimaryDiagnosisCode", b1 =>
                        {
                            b1.Property<Guid>("PatientDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PrimaryDiagnosisCode_Code");

                            b1.Property<string>("CodingSystem")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PrimaryDiagnosisCode_CodingSystem");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PrimaryDiagnosisCode_DisplayName");

                            b1.Property<string>("EntityUri")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PrimaryDiagnosisCode_EntityUri");

                            b1.HasKey("PatientDataId");

                            b1.ToTable("PatientData");

                            b1.WithOwner()
                                .HasForeignKey("PatientDataId");
                        });

                    b.Navigation("PrimaryDiagnosisCode");
                });
#pragma warning restore 612, 618
        }
    }
}
